apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}
  type: LoadBalancer
