version: 2.1

parameters:
  trigger:
    type: boolean
    default: true
  node:
    type: boolean
    default: false
  demo:
    type: boolean
    default: false

executors:
  cloud_sdk:
    docker:
      - image: google/cloud-sdk

commands:
  setup_cloud_sdk:
    steps:
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GOOGLE_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project blojchain-297012
            gcloud --quiet config set compute/zone europe-west2-a
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io

jobs:
  trigger-workflows:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Set token
          command: |
            echo "export CIRCLE_USER_TOKEN=${CIRCLE_TOKEN}" >> $BASH_ENV
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/monorepo.sh && .circleci/monorepo.sh

  build:
    parameters:      
      package_name:
        type: string
    executor: cloud_sdk
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - setup_cloud_sdk
      - run:
          name: Create Docker image
          command: |
            docker build -t blojchain-<< parameters.package_name >>:${CIRCLE_SHA1} ./app/<< parameters.package_name >>
      - run:
          name: Push Docker image
          command: |
            docker tag blojchain-<< parameters.package_name >>:${CIRCLE_SHA1} gcr.io/blojchain-297012/blojchain-<< parameters.package_name >>:${CIRCLE_SHA1}
            docker push gcr.io/blojchain-297012/blojchain-<< parameters.package_name >>:${CIRCLE_SHA1}

  deploy:
    parameters:
      package_name:
        type: string
    executor: cloud_sdk
    steps:
      - checkout
      - setup_cloud_sdk
      - run:
          name: Install Helm
          command: |
            if which helm > /dev/null; then
              exit 0
            fi
            
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
            helm version
      - run:
          name: Deploy to Kubernetes
          command: |
            cd app/<< parameters.package_name >>/helm
            ./install.sh

workflows:
  version: 2

  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows:
          filters:
              branches:
                only: master

  node:
    when: << pipeline.parameters.node >>
    jobs:
      - build:
          name: node-build
          package_name: node
      - deploy:
          name: node-deploy
          package_name: node
          requires:
            - build
  
  demo:
    when: << pipeline.parameters.demo >>
    jobs:
      - build:
          name: demo-build
          package_name: demo
      - deploy:
          name: demo-deploy
          package_name: demo
          requires:
            - build
  