version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GOOGLE_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project blojchain-297012
            gcloud --quiet config set compute/zone europe-west2-a
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
            gcloud --quiet container clusters get-credentials blojchain-cluster
      - run:
          name: Create Node Docker image
          command: docker build -t blojchain-node:${CIRCLE_SHA1} ./app/node
      - run:
          name: Push Node Docker image
          command: |
            docker tag blojchain-node:${CIRCLE_SHA1} gcr.io/blojchain-297012/blojchain-node:${CIRCLE_SHA1}
            docker push gcr.io/blojchain-297012/blojchain-node:${CIRCLE_SHA1}
      - run:
          name: Create Demo Docker image
          command: docker build -t blojchain-demo:${CIRCLE_SHA1} ./app/demo
      - run:
          name: Push Demo Docker image
          command: |
            docker tag blojchain-demo:${CIRCLE_SHA1} gcr.io/blojchain-297012/blojchain-demo:${CIRCLE_SHA1}
            docker push gcr.io/blojchain-297012/blojchain-demo:${CIRCLE_SHA1}
      - run:
          name: Install Helm
          command: |
            if which helm > /dev/null; then
              exit 0
            fi
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
            helm version
      - run:
          name: Deploy Node to Kubernetes
          command: |
            cd app/node/helm
            ./install.sh
      - run:
          name: Deploy Demo to Kubernetes
          command: |
            cd app/demo/helm
            ./install.sh
workflows:
  version: 2
  release:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
