apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: default
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: gcr.io/blojchain-297012/blojchain-node:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
        - name: SEED
          value: {{ .Values.seed }}
        - name: DELAY
          value: {{ quote .Values.delay }}
        - name: SERVER_HOST
          value: {{ .Values.server.host }}
        - name: NODE_HOST
          value: {{ .Values.node.host }}
        - name: SOCKET_HOST
          value: {{ .Values.socket.host }}
