apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
  - name: server
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: socket
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: {{ .Release.Name }}
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-swim
spec:
  ports:
  - name: swim
    port: 55356
    protocol: UDP
    targetPort: 55356
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
